/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import javax.swing.JFrame;

/**
 *
 * @author Lenovo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonMarca = new javax.swing.JButton();
        BotonProducto = new javax.swing.JButton();
        BotonStockProd = new javax.swing.JButton();
        BotonIngresarProducto = new javax.swing.JButton();
        BotonVentaProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA KARDEX");

        BotonMarca.setText("CARGA MARCAS");
        BotonMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMarcaActionPerformed(evt);
            }
        });

        BotonProducto.setText("CARGA PRODUCTOS");
        BotonProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonProductoActionPerformed(evt);
            }
        });

        BotonStockProd.setText("AJUSTES DE STOCK");
        BotonStockProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonStockProdActionPerformed(evt);
            }
        });

        BotonIngresarProducto.setText("INGRESO MERCADERIA");
        BotonIngresarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngresarProductoActionPerformed(evt);
            }
        });

        BotonVentaProducto.setText("VENTA MERCADERIA");
        BotonVentaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVentaProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonStockProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonIngresarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonVentaProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(BotonMarca)
                .addGap(18, 18, 18)
                .addComponent(BotonProducto)
                .addGap(26, 26, 26)
                .addComponent(BotonIngresarProducto)
                .addGap(18, 18, 18)
                .addComponent(BotonVentaProducto)
                .addGap(23, 23, 23)
                .addComponent(BotonStockProd)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
                                       

    private void BotonStockProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonStockProdActionPerformed
        // TODO add your handling code here:
       JFrame PantallaStockProd = new MODIF_Stock();
       
        PantallaStockProd.setVisible(true);
        
    }//GEN-LAST:event_BotonStockProdActionPerformed

    private void BotonMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMarcaActionPerformed
        // TODO add your handling code here:
        JFrame PantallaMarca = new ABM_Marca();
       
        PantallaMarca.setVisible(true);
    }//GEN-LAST:event_BotonMarcaActionPerformed

    private void BotonProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonProductoActionPerformed
        // TODO add your handling code here:
        JFrame PantallaProducto = new ABM_Producto();
       
        PantallaProducto.setVisible(true);
    }//GEN-LAST:event_BotonProductoActionPerformed

    private void BotonIngresarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngresarProductoActionPerformed
        // TODO add your handling code here:
         JFrame PantallaIngresarProducto = new INGRESAR_PRODUCTO();
       
        PantallaIngresarProducto.setVisible(true);
    }//GEN-LAST:event_BotonIngresarProductoActionPerformed

    private void BotonVentaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVentaProductoActionPerformed
        // TODO add your handling code here:
         JFrame PantallaVentaProducto = new VENTA_PRODUCTO();
       
        PantallaVentaProducto.setVisible(true);
    }//GEN-LAST:event_BotonVentaProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIngresarProducto;
    private javax.swing.JButton BotonMarca;
    private javax.swing.JButton BotonProducto;
    private javax.swing.JButton BotonStockProd;
    private javax.swing.JButton BotonVentaProducto;
    // End of variables declaration//GEN-END:variables
}
